### ISSUE TITLE
Retweets do not work in scrape mode

### ISSUE THREAD

**Issue by Vilemouse** [vegeta897/spice-bot#3]
Clicking the retweet button when using scrape mode does not have the retweeted tweet posted into discord, CMD window does not even output that it has seen said tweet.

**Comment by vegeta897** [comment]
Here's the big hurdle with retweets: I can only scrape the ID of the tweet that was retweeted, and not the retweet itself. This kind of makes life hell.

The best solution I could come up with is creating a synthetic ID for retweets based on their distance from the next non-retweet in the timeline. This allows tweets to be sorted properly, which is necessary for determining what's new, what's deleted, and how much to scrape.

This works fairly well, but things might get messy if tweets are removed from the timeline. I don't think I care enough to try to solve that problem if it comes up.

I've tested a small amount myself, but I'm leaving the issue open until you report back.

**Comment by Vilemouse** [comment]
Having only tested a small amount as well it seems to be working. However i would also leave this issue open just a little longer in case more information comes forward in terms of errors with the new method.
